
package agregado;
import javax.swing.*;
import java.awt.*;

/**
 *
 * @author steve
 */
public class Ventana extends javax.swing.JFrame {

    public Ventana() {
       
        initComponents();
    }
    private CardLayout card;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondoPrincipal = new javax.swing.JPanel();
        elegirFunciones = new javax.swing.JPanel();
        btnDerivada = new javax.swing.JButton();
        fondoDerivada = new javax.swing.JPanel();
        btnRegresar = new javax.swing.JButton();
        txtDerivada = new javax.swing.JTextField();
        textoParaDerivada = new javax.swing.JLabel();
        btnGuardarDerivada = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtVariableDerivada = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CodeMath");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fondoPrincipal.setMinimumSize(new java.awt.Dimension(800, 500));
        fondoPrincipal.setLayout(new java.awt.CardLayout());

        btnDerivada.setText("Derivada");
        btnDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDerivadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout elegirFuncionesLayout = new javax.swing.GroupLayout(elegirFunciones);
        elegirFunciones.setLayout(elegirFuncionesLayout);
        elegirFuncionesLayout.setHorizontalGroup(
            elegirFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirFuncionesLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(656, Short.MAX_VALUE))
        );
        elegirFuncionesLayout.setVerticalGroup(
            elegirFuncionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(elegirFuncionesLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(373, Short.MAX_VALUE))
        );

        fondoPrincipal.add(elegirFunciones, "elegirFunciones");

        btnRegresar.setText("<-");
        btnRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegresarActionPerformed(evt);
            }
        });

        txtDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDerivadaActionPerformed(evt);
            }
        });

        textoParaDerivada.setText("Ingrese la funcion a derivar");

        btnGuardarDerivada.setText("Generar codigo");
        btnGuardarDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarDerivadaActionPerformed(evt);
            }
        });

        jLabel1.setText("variable");

        txtVariableDerivada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtVariableDerivadaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout fondoDerivadaLayout = new javax.swing.GroupLayout(fondoDerivada);
        fondoDerivada.setLayout(fondoDerivadaLayout);
        fondoDerivadaLayout.setHorizontalGroup(
            fondoDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoDerivadaLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnGuardarDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
            .addGroup(fondoDerivadaLayout.createSequentialGroup()
                .addGroup(fondoDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fondoDerivadaLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fondoDerivadaLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(fondoDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textoParaDerivada)
                            .addComponent(txtDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(txtVariableDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(460, Short.MAX_VALUE))
        );
        fondoDerivadaLayout.setVerticalGroup(
            fondoDerivadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fondoDerivadaLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(textoParaDerivada)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtVariableDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 193, Short.MAX_VALUE)
                .addComponent(btnGuardarDerivada, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        fondoPrincipal.add(fondoDerivada, "fondoDerivada");

        getContentPane().add(fondoPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //lo siguiente son los eventos para cambiar de pestannas
    private void btnRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegresarActionPerformed
        // cambia la vista principal
        card = (CardLayout) this.fondoPrincipal.getLayout();
        card.show(fondoPrincipal, "elegirFunciones");
        this.txtDerivada.setText("");
        this.txtVariableDerivada.setText("");
        /*
        # fondoPrincipal se refiere al panel donde se estable el tipo de cardLayout
        ++ elegirFunciones se refiere al nombre que se establecio para ese apartado
        -- no siempre es el mismo, generalmente se usa card(#n) cuando se agrega en ese tipo de layout
        & yo lo cambie para que coincidiera por el nombre de la varaible jpanel
        */
        
    }//GEN-LAST:event_btnRegresarActionPerformed

    private void btnDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDerivadaActionPerformed
        // TODO add your handling code here:
        card = (CardLayout) this.fondoPrincipal.getLayout();
        card.show(fondoPrincipal, "fondoDerivada");
        /*
        # fondoPrincipal se refiere al panel donde se estable el tipo de cardLayout\
        ++ fondoDerivada se refiere al nombre que se establecio para ese apartado
        -- no siempre es el mismo, generalmente se usa card(#n) cuando se agrega en ese tipo de layout
        & yo lo cambie para que coincidiera por el nombre de la varaible jpanel
        */
    }//GEN-LAST:event_btnDerivadaActionPerformed

    private void txtDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDerivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDerivadaActionPerformed

    private void btnGuardarDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarDerivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarDerivadaActionPerformed

    private void txtVariableDerivadaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtVariableDerivadaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtVariableDerivadaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnDerivada;
    public javax.swing.JButton btnGuardarDerivada;
    public javax.swing.JButton btnRegresar;
    public javax.swing.JPanel elegirFunciones;
    public javax.swing.JPanel fondoDerivada;
    public javax.swing.JPanel fondoPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel textoParaDerivada;
    public javax.swing.JTextField txtDerivada;
    public javax.swing.JTextField txtVariableDerivada;
    // End of variables declaration//GEN-END:variables
}
